services:
  database:
    image: postgres:16.3
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    env_file:
      - ../.env
    restart: always
    expose:
      - "5432"  # Expondo apenas na rede interna do Docker para segurança

  backend:
    build:
      context: ../
      dockerfile: Dockerfile
    env_file:
      - ../.env
    depends_on:
      - database
    command: bash -c "
      python manage.py migrate --noinput &&
      python manage.py collectstatic --noinput &&
      gunicorn mysite.wsgi:application --bind 0.0.0.0:8000 ${GUNICORN_RELOAD}"
    volumes:
      - ./staticfiles/static:/docker/staticfiles/static
      - ./mediafiles:/docker/mediafiles
    restart: always

  nginx:
    image: nginx:1.27.0
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles/static:/app/staticfiles/static
      - ./mediafiles:/app/mediafiles
    ports:
      - "80:80"
    restart: always
    depends_on:
      - backend